### ISSUE TITLE
Make the bot send the mods and datapacks and update them according to the mods and datapacks in the database.

### ISSUE THREAD

**Issue by MrCookiePrincess** [PadBro/OrdinaryHelperBot#36]
Make the bot send the mods and datapacks and update them according to the mods and datapacks in the database.

gl

**Comment by PadBro** [comment]
implemented in https://github.com/PadBro/OrdinaryHelperApi/releases/tag/v1.0.0 & https://github.com/PadBro/OrdinaryHelperPanel/releases/tag/v1.2.0
